name: Feature Request
description: Request a new feature that you would like to be part of the Postman platform. 
title: "<title>"
body:
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: |
      A clear and concise description of what the problem is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: |
      A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: |
      A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: | 
      Add any other context or screenshots about the feature request here.
  validations:
    required: false
